spring:
  application:
    name: engine
  ai:
    google:
      genai:
        api-key: AIzaSyBBCBU7-xyK9tCCZ6POt18saJ0DsFNaG_w
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.2

servicenow:
  base-url: https://dev290594.service-now.com
  username: admin
  password: t0JR^RAq1r%o
  table: incident
  max-limit: 10

app:
  allowed-fields:
    - number
    - priority
    - state
    - assignment_group
    - category
    - impact
    - urgency
